imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

assetic:
    filters:
        uglifyjs:
            bin: /usr/bin/uglifyjs
            apply_to: "\.js$"
        uglifycss:
            bin: /usr/bin/uglifycss
            apply_to: "\.css$"