security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER: []
        ROLE_OLD_STAFF: ROLE _USER
        ROLE_JANITOR: [ROLE_USER, ROLE_STAFF]
        ROLE_JURY: ROLE_USER
        ROLE_COORDINATOR: [ROLE_USER, ROLE_STAFF]
        ROLE_ADMIN: [ROLE_USER, ROLE_JANITOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            switch_user: true
            remember_me:
                key: %secret%
                lifetime: 604800
                path: /
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: gamejam_compo_frontend
                always_use_default_target_path: false
                login_path: fos_user_security_login
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
