services:
    gamejam.compo.listener.game_activity:
        class: GJA\GameJam\CompoBundle\EventListener\GameActivityListener
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
        tags:
            - { name: 'kernel.event_listener', event: 'gamejam.game.activity.media', method: 'onMedia' }
            - { name: 'kernel.event_listener', event: 'gamejam.game.activity.download', method: 'onDownload' }
            - { name: 'kernel.event_listener', event: 'gamejam.game.activity.coins', method: 'onCoins' }
            - { name: 'kernel.event_listener', event: 'gamejam.game.activity.likes', method: 'onLike' }
            - { name: 'kernel.event_listener', event: 'gamejam.game.activity.creation', method: 'onCreation' }
            - { name: 'kernel.event_listener', event: 'gamejam.game.activity.info_update', method: 'onInfoUpdate' }
            - { name: 'kernel.event_listener', event: 'gamejam.game.activity.achievement', method: 'onAchievementGranted' }

    gamejam.compo.listener.game_persist:
        class: GJA\GameJam\CompoBundle\EventListener\GamePersistListener
        arguments: [@event_dispatcher]
        tags:
            - { name: 'doctrine.event_listener', event: postPersist }

    gamejam.compo.listener.user_activity:
        class: GJA\GameJam\CompoBundle\EventListener\UserActivityListener
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
        tags:
            - { name: 'kernel.event_listener', event: 'gamejam.user.activity.shout', method: 'onShout' }
            - { name: 'kernel.event_listener', event: 'gamejam.user.activity.achievement', method: 'onAchievementGranted' }

    gamejam.compo.listener.team_activity:
        class: GJA\GameJam\CompoBundle\EventListener\TeamActivityListener
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
        tags:
            - { name: 'kernel.event_listener', event: 'gamejam.compo.team_invitation.accepted', method: 'onTeamInvitationEvent' }
            - { name: 'kernel.event_listener', event: 'gamejam.compo.team_request.accepted', method: 'onTeamInvitationEvent' }

    gamejam.compo.listener.achievement_activity:
        class: GJA\GameJam\CompoBundle\EventListener\AchievementListener
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
        tags:
            - { name: 'kernel.event_listener', event: 'gamejam.compo.activity', method: 'onActivity' }

    gamejam.compo.listener.notification_listener:
        class: GJA\GameJam\CompoBundle\EventListener\NotificationListener
        arguments: [@mailer]
        tags:
            - { name: 'kernel.event_listener', event: 'gamejam.compo.notification.sent', method: 'onNotificationSent' }

    gamejam.compo.subscriber.team_invitation:
        class: GJA\GameJam\CompoBundle\EventSubscriber\TeamInvitationSubscriber
        arguments: [@gamejam.compo.notifier, @gamejam.compo.notifier.notification_builder, @event_dispatcher]
        tags:
            - { name: 'kernel.event_subscriber' }

    gamejam.compo.mailer:
        class: GJA\GameJam\CompoBundle\Service\Mailer
        arguments: [@mailer]

    gamejam.compo.notifier:
        class: GJA\GameJam\CompoBundle\Notifier\Notifier
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]

    gamejam.compo.notifier.notification_builder:
        class: GJA\GameJam\CompoBundle\Notifier\NotificationBuilder
        arguments: [@twig]